-- Supabase schema for EventFlow backend

create table if not exists users (
  id bigint generated by default as identity primary key,
  supabase_uid uuid unique,
  name text not null,
  username text unique not null,
  email text unique not null,
  role text not null default 'attendee' check (role in ('admin', 'organizer', 'attendee')),
  organizer_status text not null default 'active',
  password_hash text,
  created_at timestamptz not null default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  date date not null,
  time text not null,
  location text not null,
  category text,
  venue_type text,
  status text not null default 'Upcoming',
  approved boolean not null default false,
  capacity integer not null default 0,
  organizer_id bigint references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists registrations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  ticket_type text not null default 'General',
  qr_code text,
  created_at timestamptz not null default now(),
  unique(event_id, user_id)
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  registration_id bigint references registrations(id) on delete set null,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  checked_in_at timestamptz not null default now(),
  unique(event_id, user_id)
);

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(event_id, user_id)
);

create table if not exists engagement_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  event_id bigint references events(id) on delete set null,
  action text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table if not exists event_expenses (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  organizer_id bigint references users(id) on delete set null,
  category text,
  description text,
  amount numeric(12,2) not null default 0,
  expense_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  audience text not null default 'all',
  created_by bigint references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists admin_settings (
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  setting_value jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table users add column if not exists organizer_status text not null default 'active';
alter table events add column if not exists approved boolean not null default false;

create index if not exists idx_users_email on users(email);
create index if not exists idx_users_username on users(username);
create index if not exists idx_events_date on events(date);
create index if not exists idx_registrations_event on registrations(event_id);
create index if not exists idx_registrations_user on registrations(user_id);
create index if not exists idx_attendance_event on attendance(event_id);
create index if not exists idx_attendance_user on attendance(user_id);
create index if not exists idx_feedback_event on feedback(event_id);
create index if not exists idx_feedback_user on feedback(user_id);
create index if not exists idx_engagement_event on engagement_logs(event_id);
create index if not exists idx_event_expenses_event on event_expenses(event_id);
