-- Supabase/Postgres schema for Seamless Event Management
-- Run this first in Supabase SQL Editor

begin;

-- Keep timestamps in UTC behavior similar to the MySQL setup
set timezone = 'UTC';

-- Generic trigger to auto-update updated_at
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- =========================
-- Users and Authentication
-- =========================

create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  username varchar(100) unique,
  email varchar(100) unique not null,
  role varchar(20) not null default 'attendee' check (role in ('admin', 'organizer', 'attendee')),
  is_active boolean not null default true,
  supabase_uid uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_email on users (email);
create index if not exists idx_users_username on users (username);
create index if not exists idx_users_role on users (role);

create table if not exists admin_credentials (
  user_id bigint primary key references users(id) on delete cascade,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists organizer_credentials (
  user_id bigint primary key references users(id) on delete cascade,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists attendee_credentials (
  user_id bigint primary key references users(id) on delete cascade,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists organizer_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references users(id) on delete cascade,
  organization_name varchar(200),
  contact_phone varchar(20),
  office_address varchar(255),
  website varchar(255),
  tax_id varchar(50),
  bank_account varchar(50),
  total_events integer not null default 0,
  total_attendees integer not null default 0,
  average_rating numeric(3,2) not null default 0.00,
  verification_status varchar(20) not null default 'pending' check (verification_status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Event Management
-- =========================

create table if not exists events (
  id bigint generated by default as identity primary key,
  organizer_id bigint not null references users(id) on delete cascade,
  title varchar(200) not null,
  description text,
  date date not null,
  -- "time" is used by current Node controllers.
  time varchar(30),
  -- Keep start/end time for compatibility with existing model docs.
  start_time time,
  end_time time,
  location varchar(255),
  venue_type varchar(20) not null default 'in-person' check (venue_type in ('in-person', 'virtual', 'hybrid')),
  status varchar(20) not null default 'Planning' check (status in ('Planning', 'Live', 'Upcoming', 'Completed', 'Cancelled')),
  capacity integer not null default 0,
  registered integer not null default 0,
  checked_in integer not null default 0,
  no_show integer not null default 0,
  engagement numeric(5,2) not null default 0.00,
  avg_rating numeric(3,2) not null default 0.00,
  feedback_count integer not null default 0,
  qr_scans integer not null default 0,
  category varchar(50),
  sub_category varchar(50),
  image_url text,
  cost numeric(10,2) not null default 0.00,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_events_organizer on events (organizer_id);
create index if not exists idx_events_date on events (date);
create index if not exists idx_events_status on events (status);

create table if not exists registrations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  registration_date timestamptz not null default now(),
  ticket_type varchar(50) not null default 'General',
  payment_status varchar(20) not null default 'completed' check (payment_status in ('pending', 'completed', 'failed', 'refunded')),
  payment_method varchar(50),
  transaction_id varchar(100),
  amount_paid numeric(10,2) not null default 0.00,
  qr_code varchar(255),
  dietary_preference varchar(255),
  additional_notes text,
  cancellation_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint unique_registration unique (event_id, user_id)
);

create index if not exists idx_registrations_event on registrations (event_id);
create index if not exists idx_registrations_user on registrations (user_id);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references registrations(id) on delete cascade,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  check_in_time timestamptz not null default now(),
  check_in_method varchar(20) not null default 'QR' check (check_in_method in ('QR', 'Manual', 'App')),
  location varchar(100),
  duration_minutes integer,
  check_out_time timestamptz,
  created_at timestamptz not null default now(),
  constraint unique_attendance unique (event_id, user_id)
);

create index if not exists idx_attendance_event on attendance (event_id);
create index if not exists idx_attendance_user on attendance (user_id);

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  submitted_at timestamptz not null default now(),
  constraint unique_feedback unique (event_id, user_id)
);

create index if not exists idx_feedback_event on feedback (event_id);
create index if not exists idx_feedback_user on feedback (user_id);

create table if not exists event_vendors (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  vendor_name varchar(200) not null,
  vendor_contact varchar(255),
  vendor_email varchar(100),
  vendor_phone varchar(20),
  booth_location varchar(100),
  vendor_category varchar(100),
  payment_status varchar(20) not null default 'pending' check (payment_status in ('pending', 'partial', 'completed')),
  booth_fee numeric(10,2),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_event_vendors_event on event_vendors (event_id);

create table if not exists event_expenses (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  title varchar(200) not null,
  category varchar(100) not null default 'General',
  amount numeric(10,2) not null,
  expense_date date not null,
  payment_method varchar(50) not null default 'Other',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_event_expenses_event on event_expenses (event_id);
create index if not exists idx_event_expenses_date on event_expenses (expense_date);

create table if not exists engagement_logs (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  action varchar(100) not null,
  timestamp timestamptz not null default now()
);

create index if not exists idx_engagement_logs_event on engagement_logs (event_id);
create index if not exists idx_engagement_logs_user on engagement_logs (user_id);
create index if not exists idx_engagement_logs_time on engagement_logs (timestamp);

create table if not exists analytics (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  metric_name varchar(100) not null,
  metric_value numeric(10,2),
  metric_type varchar(20) not null default 'count' check (metric_type in ('count', 'percentage', 'average', 'total', 'rate')),
  dimension varchar(100),
  recorded_at timestamptz not null default now()
);

create index if not exists idx_analytics_event on analytics (event_id);
create index if not exists idx_analytics_metric on analytics (metric_name);

-- Admin feature tables used by controllers
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  message text not null,
  target varchar(20) not null default 'all' check (target in ('organizers', 'attendees', 'all')),
  created_by bigint,
  created_at timestamptz not null default now()
);

create table if not exists platform_settings (
  id bigint generated by default as identity primary key,
  setting_key varchar(150) not null unique,
  setting_value text not null,
  updated_at timestamptz not null default now()
);

-- Trigger wiring

drop trigger if exists trg_users_updated_at on users;
create trigger trg_users_updated_at before update on users for each row execute function set_updated_at();

drop trigger if exists trg_admin_credentials_updated_at on admin_credentials;
create trigger trg_admin_credentials_updated_at before update on admin_credentials for each row execute function set_updated_at();

drop trigger if exists trg_organizer_credentials_updated_at on organizer_credentials;
create trigger trg_organizer_credentials_updated_at before update on organizer_credentials for each row execute function set_updated_at();

drop trigger if exists trg_attendee_credentials_updated_at on attendee_credentials;
create trigger trg_attendee_credentials_updated_at before update on attendee_credentials for each row execute function set_updated_at();

drop trigger if exists trg_organizer_profiles_updated_at on organizer_profiles;
create trigger trg_organizer_profiles_updated_at before update on organizer_profiles for each row execute function set_updated_at();

drop trigger if exists trg_events_updated_at on events;
create trigger trg_events_updated_at before update on events for each row execute function set_updated_at();

drop trigger if exists trg_registrations_updated_at on registrations;
create trigger trg_registrations_updated_at before update on registrations for each row execute function set_updated_at();

drop trigger if exists trg_event_vendors_updated_at on event_vendors;
create trigger trg_event_vendors_updated_at before update on event_vendors for each row execute function set_updated_at();

drop trigger if exists trg_event_expenses_updated_at on event_expenses;
create trigger trg_event_expenses_updated_at before update on event_expenses for each row execute function set_updated_at();

drop trigger if exists trg_platform_settings_updated_at on platform_settings;
create trigger trg_platform_settings_updated_at before update on platform_settings for each row execute function set_updated_at();

commit;
